function prob = hist_prob(x, pdf_dist)
% Compute probabilities of input data in the discrete distribution.
%
% Input:
%   x [1xN (double)] N input data values from the interval [0, 1]
%   pdf [1xM (double)] PDF of the discrete distribution for M values
%     generated by linspace(0, 1, M)
%
% Output:
%   prob [1xN (double)] probabilities of N input values in the discrete
%     distribution specified by the given PDF; each input value is assigned
%     probability of the closest value from linspace(0, 1, M) 

% TODO: Replace with your own implementation.
[~,bins] = size(pdf_dist);
idx = round(x*(bins-1))+1;
prob = pdf_dist(idx);
end
